### ISSUE TITLE
Not compatible with python2.7

### ISSUE THREAD

**Issue by pyhedgehog** [dejanrizvan/node-red-contrib-python3-function#1]
```console
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c] Traceback (most recent call last):
  File "<string>", line 70, in <module>
  File "C:\tools\python27\lib\json\__init__.py", line 339, in loads
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c]     return _default_decoder.decode(s)
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c]   File "C:\tools\python27\lib\json\decoder.py", line 364, in decode
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\tools\python27\lib\json\decoder.py", line 382, in raw_decode
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c] raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
9 Mar 21:44:53 - [error] [python3-function:3d690b2f.e6883c] Python Function process exited with code 1
9 Mar 21:44:53 - [info] [python3-function:3d690b2f.e6883c] Python function '' running on PID 3144
```

I've used just `return msg` sample function.

**Comment by dejanrizvan** [comment]
Can you log the msg object before you return it?

**Comment by pyhedgehog** [comment]
Additional info:
OS: Windows 7 Pro x64
Node: v7.7.2 x64
Node-RED: v0.16.2

I don't know whose version renders both python packages incompatible, but following change fixes python2 ("older") package:
```python
    def send_to_node(self, msg):
        out = msg.dumps().encode('utf-8')
        buf = struct.pack('<llq', 1, 0, len(out))+out
        os.write(3, buf)
...
while True:
    #raw_msg = channel.readline()
    hdr = os.read(3, 16)
    if not hdr:
        raise RuntimeError('Received EOF!')
    n,t,l = struct.unpack('<llq', hdr)
    raw_msg = os.read(3, l)
    if not raw_msg:
        raise RuntimeError('Received EOF!')
    assert n == 1 and len(raw_msg) == l, str((n,t,l,len(raw_msg),repr(hdr),repr(raw_msg)))
    msg = json.loads(raw_msg.decode('utf-8'))
    msgid = msg["_msgid"]
    node = Node(msgid, channel)
```
I mean that node sends some "header" before each JSON object which contains from 4 bytes with value 1 (propose it's number of chunks), 4 bytes of unknown meaning and 8 bytes with length of remaining data (including newline character).

I think before using this code we should find where in nodejs or libuv source this format is implemented to check compatibility issues (i.e. byte-ordering on other arch's).
